from pathlib import Path
import re

ROOT=Path('_read_123_zip_20260821_180410')

video_params=ROOT/'video-request-parameters.js'
video_params.write_text(r'''/* Fuiet Infinite Canvas · video generation request parameters */
(()=>{
'use strict';
function cleanRatio(value){const raw=String(value||'16:9').trim().replace('/',':');const m=raw.match(/^(\d+(?:\.\d+)?)\s*:\s*(\d+(?:\.\d+)?)$/);if(!m)return '16:9';const w=Number(m[1]),h=Number(m[2]);return w>0&&h>0?`${m[1]}:${m[2]}`:'16:9'}
function normalizeResolution(value){const raw=String(value||'720p').trim().toLowerCase();if(['480p','720p','768p','1080p','1440p','2160p','4k'].includes(raw))return raw==='4k'?'2160p':raw;return raw||'720p'}
function standardSize(resolution='720p',aspectRatio='16:9'){const ratio=cleanRatio(aspectRatio),[rw,rh]=ratio.split(':').map(Number),portrait=rw<rh,res=normalizeResolution(resolution),high=['1080p','1440p','2160p'].includes(res);if(rw===rh)return '';if(high)return portrait?'1024x1792':'1792x1024';return portrait?'720x1280':'1280x720'}
function normalize(parameters={}){const p={...(parameters||{})};const duration=Number(p.duration??p.seconds??4),resolution=normalizeResolution(p.resolution||'720p'),aspectRatio=cleanRatio(p.aspectRatio||p.aspect_ratio||'16:9'),size=String(p.size||standardSize(resolution,aspectRatio)||'').trim();return {...p,duration,seconds:String(duration),resolution,aspectRatio,aspect_ratio:aspectRatio,size}}
function isOpenAIStandardDuration(value){return [4,8,12].includes(Number(value))}
globalThis.CanvasVideoRequestParameters=Object.freeze({cleanRatio,normalizeResolution,standardSize,normalize,isOpenAIStandardDuration});
})();
''',encoding='utf-8')

p=ROOT/'browser-runtime.js';s=p.read_text(encoding='utf-8')
s=s.replace("const ImageParams=globalThis.CanvasImageRequestParameters;","const ImageParams=globalThis.CanvasImageRequestParameters;\nconst VideoParams=globalThis.CanvasVideoRequestParameters;")
old="""async function proxyFetch(url,init={}){\n  const headers=cleanHeaders(init.headers||{});let body=init.body;\n  if(body!=null&&typeof body!=='string')throw new Error('在线代理当前只接受文本/JSON 请求体');\n  const res=await rawFetch('/api/proxy',{method:'POST',headers:{'content-type':'application/json','x-canvas-proxy':'1'},body:JSON.stringify({url,method:String(init.method||'GET').toUpperCase(),headers,body:body??null})});"""
new="""async function blobToBase64(blob){const bytes=new Uint8Array(await blob.arrayBuffer());let out='';const step=0x8000;for(let i=0;i<bytes.length;i+=step)out+=String.fromCharCode(...bytes.subarray(i,i+step));return btoa(out)}\nasync function serializeProxyBody(body){if(body==null)return{bodyType:'none',body:null};if(typeof body==='string')return{bodyType:'text',body};if(body instanceof FormData){const entries=[];for(const [name,value] of body.entries()){if(value instanceof Blob){if(value.size>25*1024*1024)throw new Error('在线预览的单个代理文件不能超过 25MB');entries.push({name,kind:'file',filename:value.name||'upload.bin',type:value.type||'application/octet-stream',base64:await blobToBase64(value)})}else entries.push({name,kind:'text',value:String(value)})}return{bodyType:'form-data',formData:entries}}throw new Error('在线代理不支持此请求体类型')}\nasync function proxyFetch(url,init={}){\n  const headers=cleanHeaders(init.headers||{}),packed=await serializeProxyBody(init.body);\n  if(packed.bodyType==='form-data'){delete headers['content-type'];delete headers['Content-Type']}\n  const res=await rawFetch('/api/proxy',{method:'POST',headers:{'content-type':'application/json','x-canvas-proxy':'1'},body:JSON.stringify({url,method:String(init.method||'GET').toUpperCase(),headers,...packed})});"""
if old not in s: raise SystemExit('proxyFetch anchor not found')
s=s.replace(old,new)
old="""async function makePortableReferences(refs=[]){const out=[];for(const r of refsForRequest(refs)){let url=r.url;if(url&&url.startsWith('blob:')){try{const res=await rawFetch(url),blob=await res.blob();if(blob.size<=15*1024*1024){url=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(blob)})}}catch{}}out.push({...r,url})}return out}"""
new="""async function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(blob)})}\nasync function referenceBlob(url){const value=String(url||'');if(!value)return null;try{if(value.startsWith('data:')){const res=await rawFetch(value);return await res.blob()}if(value.startsWith('blob:')||value.startsWith('/__browser_media/')){const res=await rawFetch(value);if(res.ok)return await res.blob()}if(/^https?:\\/\\//i.test(value)){try{const res=await rawFetch(value,{mode:'cors'});if(res.ok)return await res.blob()}catch{}const proxied=await proxyFetch(value,{method:'GET'});if(proxied.ok)return await proxied.blob()}}catch{}return null}\nasync function makePortableReferences(refs=[]){const out=[];for(const r of refsForRequest(refs)){let url=r.url;if(url&&(url.startsWith('blob:')||url.startsWith('/__browser_media/'))){try{const blob=await referenceBlob(url);if(blob&&blob.size<=20*1024*1024)url=await blobToDataUrl(blob)}catch{}}out.push({...r,url})}return out}"""
if old not in s: raise SystemExit('portable refs anchor not found')
s=s.replace(old,new)
old="""function defaultRequestBody(provider,model,task,route,refs){\n  const mod=normalizeMod(task.nodeType||model.modality),rawParams=task.parameters||{},p=mod==='image'?(ImageParams?.normalize?.(rawParams)||rawParams):rawParams,prompt=String(task.prompt||''),modelId=model.id;"""
new="""function defaultRequestBody(provider,model,task,route,refs){\n  const mod=normalizeMod(task.nodeType||model.modality),rawParams=task.parameters||{},p=mod==='image'?(ImageParams?.normalize?.(rawParams)||rawParams):mod==='video'?(VideoParams?.normalize?.(rawParams)||rawParams):rawParams,prompt=String(task.prompt||''),modelId=model.id;"""
if old not in s: raise SystemExit('request body anchor missing')
s=s.replace(old,new)
old="""  if(mod==='video'){\n    const first=refs.find(r=>['first_frame','image','image_reference'].includes(r.role)||r.type==='image');\n    const last=refs.find(r=>r.role==='last_frame');\n    return{model:modelId,prompt,...(p.duration?{duration:p.duration}:{}),...(p.resolution?{resolution:p.resolution}:{}),...(p.aspectRatio?{aspect_ratio:p.aspectRatio}:{}),...(first?.url?{image:first.url,first_frame:first.url}:{}),...(last?.url?{last_frame:last.url}:{}),...(refs.length?{references:refs}:{})};\n  }"""
new="""  if(mod==='video'){const first=refs.find(r=>['first_frame','image','image_reference'].includes(r.role)||r.type==='image');const last=refs.find(r=>r.role==='last_frame');return{model:modelId,prompt,...p,seconds:String(p.seconds||p.duration||''),...(p.size?{size:p.size}:{}),...(first?.url?{image:first.url,first_frame:first.url,input_reference:first.url}:{}),...(last?.url?{last_frame:last.url}:{}),...(refs.length?{references:refs}:{})};}\n"""
if old not in s: raise SystemExit('video json body anchor missing')
s=s.replace(old,new)
anchor="async function providerJson(provider,url,init){"
insert="""async function buildStandardVideoForm(model,task,refs){const p=VideoParams?.normalize?.(task.parameters||{})||task.parameters||{},form=new FormData();form.append('model',String(model.id||''));form.append('prompt',String(task.prompt||''));if(p.seconds)form.append('seconds',String(p.seconds));if(p.size)form.append('size',String(p.size));const first=refs.find(r=>['first_frame','image','image_reference'].includes(r.role)||r.type==='image');if(first?.url){const blob=await referenceBlob(first.url);if(!blob)throw new Error('首帧/参考图无法读取，无法提交图生视频');if(blob.size>25*1024*1024)throw new Error('首帧/参考图超过 25MB，在线预览暂不支持');form.append('input_reference',blob,'input-reference.'+((blob.type||'image/png').split('/')[1]||'png'))}return form}\nfunction autoVideoRoute(model,route){return route?.adapterKey==='standard-video-async-v1'&&(model?.routeOrigin==='auto'||model?.adapterResolved?.auto===true||!String(model?.createPath||'').trim())}\nfunction alternateVideoCreatePaths(route,model){const first=String(route.createPath||'/v1/videos');if(!autoVideoRoute(model,route))return[first];return[...new Set([first,'/v1/videos','/v1/video/generations','/v1/videos/generations'])]}\nfunction matchingPollPath(createPath,taskId,route){if(createPath==='/v1/video/generations')return `/v1/video/generations/${taskId}`;if(createPath==='/v1/videos/generations')return `/v1/videos/generations/${taskId}`;return fillTemplate(route.pollPath||'/v1/videos/{{taskId}}',{taskId})}\n"""
if anchor not in s: raise SystemExit('providerJson anchor missing')
s=s.replace(anchor,insert+anchor)
old="""async function providerJson(provider,url,init){const res=await fetchWithAuth(provider,url,init);const parsed=await readResponse(res);if(!res.ok){const detail=parsed.kind==='json'?(parsed.value?.error?.message||parsed.value?.message||JSON.stringify(parsed.value)):String(parsed.value||'');throw new Error(`供应商 HTTP ${res.status}${detail?`：${detail.slice(0,500)}`:''}`)}return parsed}"""
new="""async function providerJson(provider,url,init){const res=await fetchWithAuth(provider,url,init);const parsed=await readResponse(res);if(!res.ok){const detail=parsed.kind==='json'?(parsed.value?.error?.message||parsed.value?.message||JSON.stringify(parsed.value)):String(parsed.value||'');const err=new Error(`供应商 HTTP ${res.status}${detail?`：${detail.slice(0,500)}`:''}`);err.status=res.status;err.detail=detail;throw err}return parsed}"""
if old not in s: raise SystemExit('providerJson exact missing')
s=s.replace(old,new)
old="""  const refs=await makePortableReferences(task.references||[]),body=defaultRequestBody(provider,model,task,route,refs),createUrl=joinUrl(provider.baseUrl,route.createPath);\n  updateTask(task.id,{status:'running',progress:2,error:null});\n  const created=await providerJson(provider,createUrl,{method:route.method||'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});"""
new="""  const refs=await makePortableReferences(task.references||[]),body=defaultRequestBody(provider,model,task,route,refs);\n  updateTask(task.id,{status:'running',progress:2,error:null});\n  let created=null,usedCreatePath=route.createPath,lastCreateError=null;const paths=normalizeMod(task.nodeType)==='video'?alternateVideoCreatePaths(route,model):[route.createPath];\n  for(const createPath of paths){const createUrl=joinUrl(provider.baseUrl,createPath);try{if(route.adapterKey==='standard-video-async-v1'){try{const form=await buildStandardVideoForm(model,task,refs);created=await providerJson(provider,createUrl,{method:route.method||'POST',headers:{},body:form})}catch(error){if(![400,404,405,415,422].includes(Number(error?.status)))throw error;lastCreateError=error;created=await providerJson(provider,createUrl,{method:route.method||'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})}}else created=await providerJson(provider,createUrl,{method:route.method||'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});usedCreatePath=createPath;break}catch(error){lastCreateError=error;if(!autoVideoRoute(model,route)||![404,405].includes(Number(error?.status)))throw error}}\n  if(!created)throw lastCreateError||new Error('视频创建接口不可用');"""
if old not in s: raise SystemExit('execute create anchor missing')
s=s.replace(old,new)
s=s.replace("const pollPath=fillTemplate(route.pollPath||'/v1/videos/{{taskId}}',{taskId}),pollUrl=joinUrl(provider.baseUrl,pollPath);","const pollPath=matchingPollPath(usedCreatePath,taskId,route),pollUrl=joinUrl(provider.baseUrl,pollPath);")
p.write_text(s,encoding='utf-8')

p=ROOT/'provider-runtime-core.js';s=p.read_text(encoding='utf-8');s=s.replace("const DEFAULT_SUCCESS=['completed','succeeded','success','done','finished'];","const DEFAULT_SUCCESS=['completed','succeeded','success','done','finished','ready'];");s=s.replace("const DEFAULT_FAILURE=['failed','error','canceled','cancelled'];","const DEFAULT_FAILURE=['failed','failure','error','canceled','cancelled','rejected','expired'];");s=s.replace("'task.id','job.id','result.id'","'task.id','job.id','result.id','video.id','data.video.id','data.task.id','result.task_id','result.taskId'");s=s.replace("return firstPath(response,[config.statusPath,'status','data.status','state','data.state','task.status','job.status','result.status']);","return firstPath(response,[config.statusPath,'status','data.status','state','data.state','task.status','data.task.status','job.status','result.status','video.status','data.video.status']);");s=s.replace("'data.video_url','data.videoUrl','video_url','videoUrl','result.url','result.video_url','result.videoUrl',","'data.video_url','data.videoUrl','video_url','videoUrl','video.url','data.video.url','result.url','result.video.url','result.video_url','result.videoUrl','content_url','download_url','data.content_url','data.download_url',");p.write_text(s,encoding='utf-8')

p=ROOT/'provider-adapter-contract.js';s=p.read_text(encoding='utf-8');s=s.replace("const SUCCESS=['completed','succeeded','success','done','finished'];","const SUCCESS=['completed','succeeded','success','done','finished','ready'];");s=s.replace("const FAILURE=['failed','error','canceled','cancelled'];","const FAILURE=['failed','failure','error','canceled','cancelled','rejected','expired'];");s=s.replace("next.adapterResolved={key:route.adapterKey||'auto',ready,auto:!before.explicitAdapter,createPath:route.createPath||'',responseMode:route.responseMode||''};","next.adapterResolved={key:route.adapterKey||'auto',ready,auto:!before.explicitAdapter,createPath:route.createPath||'',responseMode:route.responseMode||''};\n  if(before.autoDefaults&&ready)next.routeOrigin='auto';");p.write_text(s,encoding='utf-8')

p=ROOT/'app.js';s=p.read_text(encoding='utf-8');s=s.replace("const resolutions=/kling/.test(t)?['720p','1080p','2160p']:/h3|minimax/.test(t)?['768p','1440p']:['480p','720p','1080p'];","const resolutions=/kling/.test(t)?['720p','1080p','2160p']:/h3|minimax/.test(t)?['768p','1440p']:/sora/.test(t)?['720p','1080p']:['480p','720p','1080p'];");s=s.replace("return{modality,durations:/seedance.*2.5/.test(t)?[4,5,10,15,30]:/h3|minimax/.test(t)?[4,5,6,8,10,12,15]:[4,5,10],resolutions,aspectRatios:['16:9','9:16','1:1','4:3','3:4']","return{modality,durations:/seedance.*2.5/.test(t)?[4,5,10,15,30]:/h3|minimax/.test(t)?[4,5,6,8,10,12,15]:/sora/.test(t)?[4,8,12]:[4,5,10],resolutions,aspectRatios:/sora/.test(t)?['16:9','9:16']:['16:9','9:16','1:1','4:3','3:4']");p.write_text(s,encoding='utf-8')

p=ROOT/'functions/api/[[path]].js';s=p.read_text(encoding='utf-8');old="""  const headers=sanitizeHeaders(body?.headers||{});\n  let payload=body?.body;\n  if(payload!==null&&payload!==undefined&&typeof payload!=='string')return json({error:'代理请求体必须是文本或 JSON 字符串'},400);\n  if(['GET','HEAD'].includes(method))payload=undefined;""";new="""  const headers=sanitizeHeaders(body?.headers||{});\n  let payload=body?.body;const bodyType=String(body?.bodyType||'text');\n  if(bodyType==='form-data'){const form=new FormData();for(const item of Array.isArray(body?.formData)?body.formData:[]){if(item?.kind==='file'){try{const bytes=Uint8Array.from(atob(String(item.base64||'')),c=>c.charCodeAt(0));form.append(String(item.name||'file'),new Blob([bytes],{type:String(item.type||'application/octet-stream')}),String(item.filename||'upload.bin'))}catch{return json({error:'代理 multipart 文件编码无效'},400)}}else form.append(String(item?.name||'field'),String(item?.value||''))}headers.delete('content-type');headers.delete('content-length');payload=form}else if(payload!==null&&payload!==undefined&&typeof payload!=='string')return json({error:'代理请求体必须是文本、JSON 字符串或 multipart'},400);\n  if(['GET','HEAD'].includes(method))payload=undefined;""";
if old not in s: raise SystemExit('proxy function anchor missing');s=s.replace(old,new);p.write_text(s,encoding='utf-8')

for name in ['index.html','models.html']:
 p=ROOT/name;s=p.read_text(encoding='utf-8');anchor='<script src="./image-request-parameters.js?v=20260828-image-dimensions-1"></script>';s=s.replace(anchor,anchor+'\n  <script src="./video-request-parameters.js?v=20260828-video-runtime-1"></script>') if 'video-request-parameters.js' not in s else s;s=s.replace('browser-runtime.js?v=20260828-image-dimensions-1','browser-runtime.js?v=20260828-video-runtime-1').replace('browser-bootstrap.js?v=20260828-image-dimensions-1','browser-bootstrap.js?v=20260828-video-runtime-1').replace('provider-runtime-core.js?v=20260828-browser-runtime-1','provider-runtime-core.js?v=20260828-video-runtime-1').replace('provider-adapter-contract.js?v=20260828-provider-model-visibility-1','provider-adapter-contract.js?v=20260828-video-runtime-1');p.write_text(s,encoding='utf-8')
p=ROOT/'browser-bootstrap.js';s=p.read_text(encoding='utf-8');s=re.sub(r"const v='[^']+';","const v='20260828-video-runtime-1';",s);p.write_text(s,encoding='utf-8')
p=ROOT/'package.json';s=p.read_text(encoding='utf-8').replace('node --check image-request-parameters.js &&','node --check image-request-parameters.js && node --check video-request-parameters.js &&');p.write_text(s,encoding='utf-8')

(ROOT/'tests/video-generation-runtime.test.mjs').write_text(r'''import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import '../video-request-parameters.js';import '../provider-runtime-core.js';const DIR=path.dirname(fileURLToPath(import.meta.url));const ROOT=path.resolve(DIR,'..');const V=globalThis.CanvasVideoRequestParameters,C=globalThis.CanvasProviderRuntimeCore;
test('standard video params map size',()=>{assert.equal(V.standardSize('720p','16:9'),'1280x720');assert.equal(V.standardSize('720p','9:16'),'720x1280');assert.equal(V.standardSize('1080p','16:9'),'1792x1024');assert.equal(V.normalize({duration:8}).seconds,'8')});
test('runtime core recognizes broader schemas',()=>{assert.equal(C.extractTaskId({data:{video:{id:'video_1'}}}),'video_1');const a=C.classifyAsyncPoll({data:{video:{status:'ready',url:'https://cdn.test/a.mp4'}}},{},'video');assert.equal(a.state,'success');assert.equal(a.output,'https://cdn.test/a.mp4');assert.equal(C.classifyAsyncPoll({status:'rejected',error:{message:'bad'}},{},'video').state,'failure')});
test('browser runtime supports multipart video and local refs',()=>{const src=fs.readFileSync(path.join(ROOT,'browser-runtime.js'),'utf8');for(const x of ['buildStandardVideoForm','input_reference','alternateVideoCreatePaths','/v1/video/generations','referenceBlob','/__browser_media/'])assert.ok(src.includes(x),x)});
test('Cloudflare proxy reconstructs multipart statelessly',()=>{const src=fs.readFileSync(path.join(ROOT,'functions/api/[[path]].js'),'utf8');assert.match(src,/bodyType==='form-data'/);assert.match(src,/new FormData\(\)/);assert.match(src,/new Blob/);assert.match(src,/no-store/)});
test('Sora defaults use 4 8 12 and landscape portrait ratios',()=>{const src=fs.readFileSync(path.join(ROOT,'app.js'),'utf8');assert.match(src,/\/sora\/\.test\(t\)\?\[4,8,12\]/);assert.match(src,/\/sora\/\.test\(t\)\?\['16:9','9:16'\]/)});
''',encoding='utf-8')
print('video generation runtime repair applied')
